name: Generate Snake

on:
  # Protidin raat 12 tay run korbe
  schedule:
    - cron: "0 0 * * *" 
  
  # Tumi chaile jokhon tokhon 'Run workflow' button click koreo chalate paro
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # Tomar GitHub username
          github_user_name: ${{ github.repository_owner }}
          # Output file kothay save hobe
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to the output branch
        uses: crazy-max/gh-action-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
